### ISSUE TITLE
docker-compose upに時間がかかる（30分）

### ISSUE THREAD

**Issue by yasuda0320** [ChubachiPT21/paddle#13]
docker-compose upを行うと、Fetching packagesで1562個のダウンロードが行われ、最後に以下のエラーが表示されて38000個のパッケージがダウンロードされてlocalhost:13000/appが見られるようになるまで30分かかってしまいます。これからエラーメッセージについて調べてみようとは思いますが、何かご存じの方はいませんでしょうか。ちなみにもう一台のMacBook Air 2015だと数分で立ち上がります。

info fsevents@2.3.2: The platform "linux" is incompatible with this module.
info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.13: The platform "linux" is incompatible with this module.
info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.

環境は以下のとおりです。
---
macOS Catalina 10.15.7
MacBook Air 13-inchi 2019

% docker -v
Docker version 20.10.5, build 55c4c88
% docker-compose -v 
docker-compose version 1.29.0, build 07737305

**Comment by hrkmr-tech** [comment]
まず、これはエラーではなくmacOS用のモジュールなのでLinuxにはインストールする必要はないとメッセージは言ってます。`fsevents`というのは、macOSのファイル変更があったときにネイティブイベントを補足しフロントエンドのモジュールバンドラに伝え自動リロードを実行するために使われます。

**Comment by yasuda0320** [comment]
メッセージの内容もなのですが、単にgit pullしてとある環境では何もエラーが表示されず、ほぼ同じと思われる別の環境ではエラーになってupに30分かかるという点が疑問なのです。落とし穴が何なのかがわからないということです。

**Comment by hrkmr-tech** [comment]
コンテナを使用しない`nodenv`を使用したフロントエンド起動方法だと高速です。READMEに方法を記載したいと思います。

**Comment by yasuda0320** [comment]
node_modulesをホストとコンテナで分離する方向で試してみます。
